name: ChessChaos.Common Tests (.NET 7, Ubuntu Latest)

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      common-working-directory: ./src/ChessChaos.Common
      common-tests-working-directory: ./src/ChessChaos.CommonTests
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore ChessChaos.Common
      run: dotnet restore
      working-directory: ${{env.common-working-directory}}

    - name: Build ChessChaos.Common
      run: dotnet build --no-restore
      working-directory: ${{env.common-working-directory}}
    
    - name: Restore ChessChaos.CommonTests
      run: dotnet restore
      working-directory: ${{env.common-tests-working-directory}}

    - name: Build ChessChaos.CommonTests
      run: dotnet build --no-restore
      working-directory: ${{env.common-tests-working-directory}}

    - name: Run tests for ChessChaos.CommonTests
      run: dotnet test --no-build --no-restore
      working-directory: ${{env.common-tests-working-directory}}